# Generated by Django 5.0.3 on 2024-04-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenamientoMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_almacenamiento', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'almacenamiento_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Almacenamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'almacenamientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conmutadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnologia', models.CharField(blank=True, max_length=255, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=255, null=True)),
                ('ext_soportadas', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'conmutadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConmutadoresMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_conmutador', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'conmutadores_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dependencia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dependencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_uso', models.CharField(blank=True, max_length=250, null=True)),
                ('num_rotores', models.CharField(blank=True, max_length=250, null=True)),
                ('metodo_vuelo', models.CharField(blank=True, max_length=255, null=True)),
                ('radio_alcance', models.CharField(blank=True, max_length=250, null=True)),
                ('resolucion_camara', models.CharField(blank=True, max_length=255, null=True)),
                ('bateria', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'drones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DronesCaracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'drones_caracteristicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnergiaMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_energia', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'energia_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Energias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'energias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('ancho_banda', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enlaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnlacesTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_enlace', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'enlaces_tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=55, null=True)),
                ('modelo', models.CharField(blank=True, max_length=55, null=True)),
                ('velocidad_procesador', models.CharField(blank=True, max_length=55, null=True)),
                ('ram', models.CharField(blank=True, max_length=30, null=True)),
                ('so', models.CharField(blank=True, max_length=255, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=55, null=True)),
                ('cantidad_puertos', models.IntegerField(blank=True, null=True)),
                ('capacidad_disco', models.CharField(blank=True, max_length=55, null=True)),
                ('arquitectura', models.CharField(blank=True, max_length=10, null=True)),
                ('licencia', models.BooleanField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo_pantalla', models.CharField(blank=True, max_length=255, null=True)),
                ('conexion_pantalla', models.CharField(blank=True, max_length=255, null=True)),
                ('tamano', models.CharField(blank=True, max_length=55, null=True)),
                ('mac_alambrica', models.CharField(blank=True, max_length=50, null=True)),
                ('mac_inalambrica', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'equipos_personales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposPersonalesMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_equipopersonal', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'equipos_personales_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposPersonalesTipopuertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'equipos_personales_tipopuertos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposServidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('criticidad', models.CharField(blank=True, max_length=255, null=True)),
                ('proposito', models.CharField(blank=True, max_length=255, null=True)),
                ('velocidad', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('opc', models.BooleanField(blank=True, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('periodo_respaldo', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_nucleos', models.CharField(blank=True, max_length=100, null=True)),
                ('config_disco', models.CharField(blank=True, max_length=255, null=True)),
                ('software', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_interna', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('licencia_so', models.BooleanField(blank=True, null=True)),
                ('tipo_respaldo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'equipos_servidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposServidoresMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_equipopersonal', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'equipos_servidores_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposServidoresTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipopersonal', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'equipos_servidores_tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoTelefonico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('tipo_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_linea', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_ext', models.CharField(blank=True, max_length=255, null=True)),
                ('num', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'equipo_telefonico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firewalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('cant_puertos', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_almacenamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('chasis', models.CharField(blank=True, max_length=255, null=True)),
                ('cant_fuentes_poder', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('troughput', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'firewalls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FirewallsMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_firewall', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'firewalls_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HerramientaDeDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_licencias', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_licencias', models.CharField(blank=True, max_length=255, null=True)),
                ('version_herramienta', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('uso_licencia', models.CharField(blank=True, max_length=255, null=True)),
                ('uso_sin_licencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'herramienta_de_desarrollo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impresoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('imprime_color', models.BooleanField(blank=True, null=True)),
                ('conexion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_impresion', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'impresoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImpresorasMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_impresora', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'impresoras_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('forma_conexion_internet', models.CharField(blank=True, max_length=100, null=True)),
                ('conexion_pc', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'proyectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoresMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_proyector', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'proyectores_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('num_tarjetas', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'routers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secretarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_secretaria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secretarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaDeInformacionMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_desarrollo', models.CharField(blank=True, max_length=255, null=True)),
                ('framework', models.CharField(blank=True, max_length=255, null=True)),
                ('bd', models.CharField(blank=True, max_length=255, null=True)),
                ('opc', models.BooleanField(blank=True, null=True)),
                ('disponible', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_supervisores', models.CharField(blank=True, max_length=255, null=True)),
                ('anios_en_operacion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('uso', models.CharField(blank=True, max_length=255, null=True)),
                ('derechos', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisores', models.CharField(blank=True, max_length=255, null=True)),
                ('operacionales', models.CharField(blank=True, max_length=255, null=True)),
                ('ejecutivos', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sistema_de_informacion_movil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaInformacionMovilNombres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistemainfo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sistema_informacion_movil_nombres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemasInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('esquema', models.CharField(blank=True, max_length=255, null=True)),
                ('lenguaje', models.CharField(blank=True, max_length=255, null=True)),
                ('bd', models.CharField(blank=True, max_length=255, null=True)),
                ('opc', models.BooleanField(blank=True, null=True)),
                ('uso', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_supervisores', models.CharField(blank=True, max_length=100, null=True)),
                ('anios_en_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('derechos', models.BooleanField(blank=True, null=True)),
                ('supervisores', models.CharField(blank=True, max_length=100, null=True)),
                ('operacionales', models.CharField(blank=True, max_length=100, null=True)),
                ('ejecutivos', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sistemas_informacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemasInformacionNombres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistemainfo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sistemas_informacion_nombres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('no_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('metros', models.FloatField(blank=True, null=True)),
                ('opc', models.BooleanField(blank=True, null=True)),
                ('capacidad_aire', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_piso', models.CharField(blank=True, max_length=255, null=True)),
                ('incendio', models.CharField(blank=True, max_length=255, null=True)),
                ('cableado', models.BooleanField(blank=True, null=True)),
                ('respaldo_energia', models.BooleanField(blank=True, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tecnologias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('contrasenia', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellio_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('num_empleado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConmutadoresPuertos',
            fields=[
                ('id_conmutador', models.OneToOneField(db_column='id_conmutador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.conmutadores')),
                ('puerto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'conmutadores_puertos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DronesAsignacionCaracteristicas',
            fields=[
                ('id_dron', models.OneToOneField(db_column='id_dron', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.drones')),
            ],
            options={
                'db_table': 'drones_asignacion_caracteristicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposPersonalesPuertos',
            fields=[
                ('id_equipo_personal', models.OneToOneField(db_column='id_equipo_personal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.equipospersonales')),
                ('mac', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'equipos_personales_puertos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposServidoresProcesadores',
            fields=[
                ('id_equipo_servidor', models.OneToOneField(db_column='id_equipo_servidor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.equiposservidores')),
                ('procesador', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'equipos_servidores_procesadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposServidoresPuertos',
            fields=[
                ('id_equipo_servidor', models.OneToOneField(db_column='id_equipo_servidor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.equiposservidores')),
                ('puerto', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'equipos_servidores_puertos',
                'managed': False,
            },
        ),
    ]
