# Generated by Django 5.0.3 on 2024-04-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usuarios_groups_usuarios_id_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
