# Generated by Django 5.0.3 on 2024-04-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='main_usuarios',
        ),
    ]
