# Generated by Django 5.0.3 on 2024-04-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
