# Generated by Django 5.0.3 on 2024-04-30 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_usuarios_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            #preserve_default=False,
        ),
    ]
