# Generated by Django 5.0.3 on 2024-05-01 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_usuarios_groups_remove_usuarios_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
